### ISSUE TITLE
CI: ImportError: cannot import name 'AsyncGeneratorType

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1306]
see eg https://travis-ci.org/crossbario/autobahn-python/jobs/646036129

```
python/.tox/coverage/bin/python

cachedir: .tox/coverage/.pytest_cache

rootdir: /home/travis/build/crossbario/autobahn-python, inifile: setup.cfg

plugins: asyncio-0.10.0, twisted-1.12

collected 172 items / 7 errors / 165 selected                                  

==================================== ERRORS ====================================

_ ERROR collecting .tox/coverage/lib/python3.5/site-packages/autobahn/asyncio/test/test_asyncio_rawsocket.py _

ImportError while importing test module '/home/travis/build/crossbario/autobahn-python/.tox/coverage/lib/python3.5/site-packages/autobahn/asyncio/test/test_asyncio_rawsocket.py'.

Hint: make sure your test modules/packages have valid Python names.

Traceback:

.tox/coverage/lib/python3.5/site-packages/autobahn/asyncio/test/test_asyncio_rawsocket.py:6: in <module>

    from autobahn.asyncio.rawsocket import PrefixProtocol, RawSocketClientProtocol, RawSocketServerProtocol, \

.tox/coverage/lib/python3.5/site-packages/autobahn/asyncio/__init__.py:32: in <module>

    from autobahn.asyncio.websocket import \

.tox/coverage/lib/python3.5/site-packages/autobahn/asyncio/websocket.py:33: in <module>

    txaio.use_asyncio()

.tox/coverage/lib/python3.5/site-packages/txaio/__init__.py:124: in use_asyncio

    from txaio import aio

.tox/coverage/lib/python3.5/site-packages/txaio/aio.py:30: in <module>

    from types import AsyncGeneratorType

E   ImportError: cannot import name 'AsyncGeneratorType'
```

**Comment by om26er** [comment]
I'll fix that.

**Comment by om26er** [comment]
issue caused by https://github.com/crossbario/txaio/commit/61268da182698325b9a1076c4f601dd3a4523822

**Comment by om26er** [comment]
fix is here https://github.com/crossbario/txaio/pull/157

**Comment by oberstet** [comment]
I've restarted the previously failed job:

* https://travis-ci.org/crossbario/autobahn-python/jobs/646036129

In theory, it should work, as the `coverage` tox target fetches txaio master: https://github.com/crossbario/autobahn-python/blob/master/tox.ini#L108

**Comment by oberstet** [comment]
yes, that worked! cool .. closing

> sidenote: rgd removing last py2 lines of code from CB and your respective PR: pls see https://github.com/crossbario/crossbar/pull/1693#issuecomment-581276881

**Comment by oberstet** [comment]
fix via https://github.com/crossbario/txaio/pull/157
