### ISSUE TITLE
Please update examples

### ISSUE THREAD

**Issue by pwfraley** [crossbario/autobahn-python#676]
I found that none of the wamp examples I tried are working.  I have Version 0.14.0 installed and also tried the examples from this tag, but either they give a:
ConnectionRefusedError
or a:
got an unexpected keyword argument 'standalone' error.

This is really frustrating, for two reasons: I am relatively new to python (well 10 years of on and off experience with flask and django) and I am completely new to WAMP and twisted.  I do know RPC and also SOAP and I find the Idea doing something like this across websockets very compelling, but I have spent now 3 hours trying some of the examples and trying to correct them, but with no luck so far.

For each example I have a virtualenv setup and installed:
```
pip install autobahn[twisted,accelerate,compress,serialization]
```
Am I missing something?

Please keep up this cool project :)

**Comment by cooltrane** [comment]
Also the examples for the asyncio version are in the old style (yield from, and not with async/await) ->https://github.com/crossbario/autobahn-python/blob/master/examples/asyncio/websocket/echo/client_coroutines.py for example.

Even if for the moment it actually still works fine with python3.5, I found it confusing when learning to use asyncio, and autobahn.

This situation leeds to confusion when searching for examples for pure asyncio, and stumble here and find ```@asyncio.coroutine``` decorator and so on ...

**Comment by meejah** [comment]
@pwfraley we do test the examples periodically with the `run-all-examples.sh` script. I ran that just now on crossbar master and it ran fine -- what examples were you trying, on what OS, with which crossbar/autobahn version (you can run `crossbar version` to dump these).

**Comment by oberstet** [comment]
works for me

**Comment by pwfraley** [comment]
Sorry for the late reply.

I had used it on Ubuntu 16.04 with version 0.14.0.  Which crossbar version I was using I do not know anymore, since I had to switch to something else to get the project done.

I ran it on the stock python from ubuntu 16.04 with a virtual env and installed the requirements like I stated in the original post.

**Comment by meejah** [comment]
Note also that we've updated the Python3 examples to use `async` / `await` now, too.
